#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/tlrt_gateway
LOG_DIR=/var/vcap/sys/log/tlrt_gateway
PIDFILE=$RUN_DIR/tlrt_gateway.pid

JOB_DIR=/var/vcap/jobs/tlrt_gateway

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Tlrt gateway"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    exec /var/vcap/packages/tlrt_gateway/services/ng/tlrt/bin/tlrt_gateway \
         -c $JOB_DIR/config/tlrt_gateway.yml \
         >>$LOG_DIR/tlrt_gateway.stdout.log \
         2>>$LOG_DIR/tlrt_gateway.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: tlrt_gateway_ctl {start|stop}"

    ;;

esac
