#!/bin/bash
<%
lifecycle = properties.service_lifecycle
%>
export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/wtp_node
LOG_DIR=/var/vcap/sys/log/wtp_node
SERV_LOG_DIR=/var/vcap/sys/service-log/wtp
PIDFILE=$RUN_DIR/wtp_node.pid
JOB_DIR=/var/vcap/jobs/wtp_node
<% if lifecycle and lifecycle.nfs_server %>
SNAPSHOT_DIR=<%= lifecycle.mount_point || "/var/vcap/services_snapshot" %>
MT_OPTS="-t nfs"
MT_EXPORT=<%= lifecycle.nfs_server.address %>:<%= lifecycle.nfs_server.export_dir %>
<% end %>

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    sysctl -w net.ipv4.ip_local_port_range="20000 45000"
    pid_guard $PIDFILE "Tlrt"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    mkdir -p $SERV_LOG_DIR

    echo $$ > $PIDFILE

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    mkdir -p $MIG_DIR
    <% if lifecycle %>
    mkdir -p $SNAPSHOT_DIR
    check_mount "$MT_OPTS" "$MT_EXPORT" "$SNAPSHOT_DIR"
    <% end %>

    exec /var/vcap/packages/wtp_node/services/ng/wtp/bin/wtp_node \
         -c $JOB_DIR/config/wtp_node.yml \
         >>$LOG_DIR/wtp_node.stdout.log \
         2>>$LOG_DIR/wtp_node.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE


    <% if lifecycle %>
    umount $SNAPSHOT_DIR
    <% end %>

    ;;

  *)
    echo "Usage: wtp_node_ctl {start|stop}"

    ;;

esac
